export enum imageList {
    BLUEFISH ='blueFish.jpg',
    GREENFISH = 'greenFish.jpg',
    LOBSTER = 'lobster.jpg',
    OCTOPUTS = 'octopus.jpg',
    REDFISH = 'redFish.jpg',
    SEAHORSE = 'seaHorse.jpg',
    SEASTAR = 'seaStar.jpg',
    TURTLE = 'turtle.jpg',
    BLUEFISH1 = 'blueFish1.jpg',
    BLUEFISH3 = 'blueFish3.jpg',
    BLUEFISH6 = 'blueFish6.jpg',
    BLUEMED = 'blueMed.jpg',
    BLUEWHALE = 'blueWhale.jpg',
    BLUEWHALE3 = 'blueWhale3.jpg',
    BROWNFISH = 'brownFish.jpg',
    CRAB2 = 'crab2.jpg',
    CRABINSHELL = 'crabInShell.jpg',
    GRAY = 'gray.jpg',
    GREENFISH4 = 'greenFish4.jpg',
    GREENFISH5 = 'greenFish5.jpg',
    GREENLIGHTFISH = 'greenLightFish.jpg',
    YELLOW = 'yellow3.jpg',
    PINK3 = 'pink3.jpg',
    PIKCRAB = 'pikCrab.jpg',
    PINKFISH = 'pinkFish.jpg',
    PINKFISH2 = 'pinkFish2.jpg',
    PINKFISH5 = 'pinkFish5.jpg',
    PINKSEAHORSE = 'pinkSeahorse.jpg',
    PINKSHELL = 'pinkShell.jpg',
    PINKSTAR = 'pinkStar.jpg',
    PLATE = 'plate.jpg',
    PNK3 = 'pnk3.jpg',
    SEADOG = 'seaDog.jpg',
    SEASTARRED= 'seaStarRed.jpg',
    SEASTARYELLOW = 'seaStarYellow.jpg',
    SHARK = 'shark.jpg',
    SHELLEYES = 'shellEyes.jpg',
    STAFIL = 'stafil.jpg',
    TURTLE1 = 'turtle1.jpg',
    WHALE = 'whale.jpg',
    WHALE2 = 'whale2.jpg',
    YELLOW3 = 'yellow3.jpg',
    YELLOWCRAB = 'yellowCrab.jpg',
    YELLOW3CRAD = 'yellowCrad.jpg',
    YELLOWFISH5 = 'yellowFish5.jpg',
    YELLOWFISHBLUE = 'yellowFishBlue.jpg'
}

export enum levelImages {
    LEVEL1 = 'level1.PNG',
    LEVEL2 = 'level2.PNG',
    LEVEL3 = 'level3.PNG',
    LEVEL4 = 'level4.PNG',
    LEVEL5 = 'level5.PNG',
    LEVEL6 = 'level6.PNG',
    LEVEL7 = 'level7.PNG',
    LEVEL8 = 'level8.PNG',
    LEVEL9 = 'level9.PNG',
    LEVEL10 = 'level10.PNG',
}

export enum skills {
    BACKSTROKE = 'Swims Backstroke',
    BREASTSTROKE = 'Swims Breaststroke',
    FREESTYLE = 'Swims Freestyle',
    BUTTERFLY = 'Swims Butterfly',
    HEADDIVE = 'Head dive in the pool',
    HOLD25 = 'Hold breath more than 25 seconds',
    BUTTERFLYUNDERWATER = 'Can do underwater Butterfly kicks',
    LAP30 = 'Swims one lap less than 30 seconds',
    FREETURN = 'Can do freestyle flip turn',
    LAPS8 = 'Can do 8 laps(200m) without brake'
}

export enum kidsSkills {
    JUMP = 'Jumps in the water',
    PUTSHEAD = 'Puts head underwater',
    HOLDBREATH10 = 'Hold breath more than 10 seconds',
    DIVESBOTTOM = 'Swims to the bottom(1.5m)',
    BACKFLOAT = 'Lies on back and floats',
    BACKSTROKE = 'Swims Backstroke',
    BREASTSTROKE = 'Swims Breaststroke',
    ALONE5 = 'Swims 5-7 meters alone',
    HEADDIVE = 'Head dive in the pool',
    ACCROSSPOOL = 'Swims across the pool(25m)',
}